### ISSUE TITLE
Installation Issues..

### ISSUE THREAD

**Issue by skampala1** [cavenel/ev3-print3rbot#5] opened 2015-10-20 13:15 UTC
Hello @cavenel ...
I got a doubt...after installing ev3 dev on my ubuntu terminal... after typing this command : apt-get install libboost-python-dev python-setuptools python-pil ...I get an error as :

Package python-setuptools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source.

Then I typed : git clone https://github.com/cavenel/ev3-print3rbot.git
cd ev3-print3rbot/
and I got the error as : -bash: git: command not found 
-bash: cd: ev3-print3rbot/: No such file or directory

Then I tried the other way , ie. : chmod +x writer.py

I got the error as : chmod: cannot access ‘writer.py’: No such file or directory 

Please help me out..! It would be a great help..! Thanks in advance..:)

**Comment by cavenel** [comment] 2015-10-20 13:20
What do you mean by "after installing ev3 dev on my ubuntu terminal"?
You have to launch all these commands on the ev3, connected through ssh. Not directly on your ubuntu terminal. See http://www.ev3dev.org/docs/tutorials/connecting-to-the-internet-via-usb/ for connecting to ev3 via ssh.

**Comment by skampala1** [comment] 2015-10-20 13:22
Yes...! I connected through ssh, and after typing those commands in that, I got those errors..! 

Here's what I actually did :

root@ev3dev:~# apt-get install libboost-python-dev python-setuptools python-pil
Reading package lists... Done
Building dependency tree... Done
Package python-setuptools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package libboost-python-dev
E: Package 'python-setuptools' has no installation candidate
E: Unable to locate package python-pil
root@ev3dev:~# easy_install -U python-ev3dev
-bash: easy_install: command not found
root@ev3dev:~#

**Comment by skampala1** [comment] 2015-10-20 13:28
Will these be of any help : http://askubuntu.com/questions/350312/i-am-not-able-to-install-easy-install-in-my-ubuntu ?

**Comment by cavenel** [comment] 2015-10-20 13:31
Not really. The problem is not on Ubuntu but on the EV3 directly.
You have to be sure that the internet connection is working on the ev3, and do an update of package list before trying to install stuff:

```
apt-get update
```

Just give me the output of this command for now.

**Comment by skampala1** [comment] 2015-10-20 13:34
root@ev3dev:~# apt-get update
Ign http://ftp.debian.org jessie InRelease
Get:1 http://ftp.debian.org jessie Release.gpg [2,373 B]
Get:2 http://ftp.debian.org jessie Release [148 kB]                          
Get:3 http://ev3dev.org jessie InRelease [8,397 B]
Get:4 http://ev3dev.org jessie/main armel Packages [15.8 kB]   
Get:5 http://ftp.debian.org jessie/main armel Packages [6,622 kB]
Ign http://ev3dev.org jessie/main Translation-en_US                            
Ign http://ev3dev.org jessie/main Translation-en                               
Get:6 http://ftp.debian.org jessie/contrib armel Packages [37.1 kB]            
Get:7 http://ftp.debian.org jessie/non-free armel Packages [59.7 kB]           
Get:8 http://ftp.debian.org jessie/contrib Translation-en [38.4 kB]            
Get:9 http://ftp.debian.org jessie/main Translation-en [4,585 kB]              
Get:10 http://ftp.debian.org jessie/non-free Translation-en [72.2 kB]          
100% [9 Translation-en bzip2 0 B] [5 Packages xz 0 B]

**Comment by skampala1** [comment] 2015-10-20 13:36
Okay...doing it right now...

Done. 
Here it is :

root@ev3dev:~# apt-get update
Ign http://ftp.debian.org jessie InRelease
Get:1 http://ftp.debian.org jessie Release.gpg [2,373 B]
Get:2 http://ftp.debian.org jessie Release [148 kB]  
Get:3 http://ev3dev.org jessie InRelease [8,397 B]
Get:4 http://ev3dev.org jessie/main armel Packages [15.8 kB]  
Get:5 http://ftp.debian.org jessie/main armel Packages [6,622 kB]
Ign http://ev3dev.org jessie/main Translation-en_US  
Ign http://ev3dev.org jessie/main Translation-en  
Get:6 http://ftp.debian.org jessie/contrib armel Packages [37.1 kB]  
Get:7 http://ftp.debian.org jessie/non-free armel Packages [59.7 kB]  
Get:8 http://ftp.debian.org jessie/contrib Translation-en [38.4 kB]  
Get:9 http://ftp.debian.org jessie/main Translation-en [4,585 kB]  
Get:10 http://ftp.debian.org jessie/non-free Translation-en [72.2 kB]  
100% [9 Translation-en bzip2 0 B] [5 Packages xz 0 B]  
100% [9 Translation-en bzip2 0 B] [5 Packages xz 0 B]
Fetched 11.6 MB in 2min 49s (68.2 kB/s)  
Reading package lists... Done
root@ev3dev:~# 
root@ev3dev:~# 
root@ev3dev:~#

**Comment by cavenel** [comment] 2015-10-20 13:38
Ok. Then upgrade the system:

```
apt-get dist-upgrade
```

And then install setuptools:

```
apt-get install libboost-python1.55.0 python-setuptools python-pil
```

Tell me if you still have the same problem then.

**Comment by skampala1** [comment] 2015-10-20 13:40
Okay...doing it now....

**Comment by skampala1** [comment] 2015-10-20 13:45
Doing it now..

**Comment by skampala1** [comment] 2015-10-20 13:49
Done...Wow..Thanks...it worked like charm..! 
Here's the last line : Setting up libboost-python1.55.0 (1.55.0+dfsg-3) ...
Setting up libfreetype6:armel (2.5.2-3) ...
Setting up liblcms2-2:armel (2.6-3+b3) ...
Setting up libwebp5:armel (0.4.1-1.2+b2) ...
Setting up libwebpdemux1:armel (0.4.1-1.2+b2) ...
Setting up libwebpmux1:armel (0.4.1-1.2+b2) ...
Setting up python-pil:armel (2.6.1-2) ...
Setting up python-setuptools (5.5.1-1) ...
Processing triggers for libc-bin (2.19-18+deb8u1) ...
root@ev3dev:~# 

Now running : easy_install -U python-ev3dev
Worked... !

**Comment by skampala1** [comment] 2015-10-20 13:52
Oh..! :( Now I tried : git clone https://github.com/cavenel/ev3-print3rbot.git
cd ev3-print3rbot/ ...
I got the error as : 

root@ev3dev:~# git clone https://github.com/cavenel/ev3-print3rbot.git
-bash: git: command not found
root@ev3dev:~# cd ev3-print3rbot/
-bash: cd: ev3-print3rbot/: No such file or directory
root@ev3dev:~# chmod +x writer.py
chmod: cannot access ‘writer.py’: No such file or directory
root@ev3dev:~# 

What should I do now...?

**Comment by cavenel** [comment] 2015-10-20 13:53
Great! Now last issue is with git not being installed (as you have the error message: `-bash: git: command not found`)
I thought git was install on ev3. Apparently it is not (anymore?)
So try:

```
apt-get install git
git clone https://github.com/cavenel/ev3-print3rbot.git
```

and let me know :)

**Comment by skampala1** [comment] 2015-10-20 13:54
Okay...doing it...

**Comment by skampala1** [comment] 2015-10-20 14:00
Did..cloned... :) WOW..! 

root@ev3dev:~# git clone https://github.com/cavenel/ev3-print3rbot.git
Cloning into 'ev3-print3rbot'...
remote: Counting objects: 64, done.
remote: Total 64 (delta 0), reused 0 (delta 0), pack-reused 64
Unpacking objects: 100% (64/64), done.
Checking connectivity... done.
root@ev3dev:~# python writer.py
python: can't open file 'writer.py': [Errno 2] No such file or directory
root@ev3dev:~# chmod +x writer.py
chmod: cannot access ‘writer.py’: No such file or directory
root@ev3dev:~# 

But when I did python writer.py , I got that error... :(

**Comment by cavenel** [comment] 2015-10-20 14:03
Maybe you forgot `cd ev3-print3rbot/` before doing `python writer.py`?
At least now with this issue we have all the detailed procedure! I updated the instruction page to include installation of git and update of packages.

**Comment by skampala1** [comment] 2015-10-20 14:07
Ah...! Now..it works..! You are great...! :) ...So, just to clarify, in order to change the svg file...should I replace that template.svg ?

**Comment by cavenel** [comment] 2015-10-20 14:09
No, you should replace the test.svg file, or change the image filename in writer.py line 477:

```
wri.draw_image(image_file = 'images/test.svg',max_speed=50)
```

Change `images/test.svg` with the path to your own image.

See https://github.com/cavenel/ev3-print3rbot#drawing-an-svg-image for more information on what the svg file should contain and so on.

But you should make sure that everything works with the default image before trying a custom image.

**Comment by skampala1** [comment] 2015-10-20 14:12
Um..and is there any way to make the image drawn bigger ?

**Comment by cavenel** [comment] 2015-10-20 14:18
Unfortunately, the image size is limited by the arms of the robot. It can only draw in the area accessible by the pen... The actual code is trying to fit the bounding box of your image in this accessible area. Thus sometimes the drawing can be quite small. I will not have time to go more into details today.

**Comment by skampala1** [comment] 2015-10-20 14:20
Oh..! Okay..I tried removing transforms for my svg file... And it went like this : 

skampala@skampala:~$ inkscape --verb=EditSelectAll --verb=ObjectToPath --verb=SelectionUnGroup --verb=FileSave --verb=FileClose --verb=FileQuit test1.svg

*\* (inkscape:25401): CRITICAL *_: Inkscape::XML::Document_ sp_repr_read_file(const gchar_, const gchar_): assertion 'Inkscape::IO::file_test( filename, G_FILE_TEST_EXISTS )' failed
**
ERROR:verbs.cpp:797:static void Inkscape::FileVerb::perform(SPAction_, void_, void*): assertion failed: (parent != NULL)

Emergency save activated!
Emergency save completed. Inkscape will close now.
If you can reproduce this crash, please file a bug at www.inkscape.org
with a detailed description of the steps leading to the crash, so we can fix it.
Aborted (core dumped)
skampala@skampala:~$

**Comment by skampala1** [comment] 2015-10-20 14:24
Can you please tell the steps to remove transforms directly from Inkscape..? Please..

**Comment by cavenel** [comment] 2015-10-20 14:24
We are a bit out of the scope of the issue, so maybe I will close it, but we can continue the discussion here anyway.
It says:

```
assertion 'Inkscape::IO::file_test( filename, G_FILE_TEST_EXISTS )' failed
```

I think that means that it didn't find the file `test1.svg`. Are you sure you have a file named `test1.svg` and that you are in the same folder as `test1.svg` (your terminal says that you are directly in your home folder, is `test1.svg` in it?)

**Comment by skampala1** [comment] 2015-10-20 14:29
Thanks....Thank you soo much...!

**Closed as completed** 2015-10-20 14:37 UTC
